version: "3.7"
services:
  perfectworld-authd:
    container_name: perfectworld-authd
    depends_on:
      - perfectworld-uniquenamed
    expose:
      - "29200/tcp"
    restart: always
    environment:
      AUTHD_SERVER_ADDRESS: 0.0.0.0
      AUTHD_SERVER_PORT: 29200
      MYSQL_ADDRESS: ${DB_HOST}
      MYSQL_PORT: ${DB_PORT}
      MYSQL_DB: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      TZ: Asia/Jakarta
    image: ossperfectworld/perfect-world-authd:latest
    networks:
      - infrastructure
  # perfectworld-db:
  #   container_name: perfectworld-db
  #   image: mysql:5.7
  #   restart: always
  #   expose:
  #     - "3306/tcp"
  #   volumes:
  #     - ./sql:/docker-entrypoint-initdb.d
  #     - perfectworld-mysql-volume:/var/lib/mysql
  #   networks:
  #     - infrastructure
  #   environment:
  #     MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
  #     MYSQL_DATABASE: ${DB_NAME}
  #     MYSQL_USER: ${DB_USERNAME}
  #     MYSQL_PASSWORD: ${DB_PASSWORD}
  #     TZ: Asia/Jakarta
  perfectworld-gacd:
    container_name: perfectworld-gacd
    depends_on:
        - perfectworld-gamedbd
    expose:
      - "29702/tcp"
      - "29712/tcp"
    restart: always
    environment:
      LOGSERVICE_SERVER_UDP_PORT: 11100
      LOGSERVICE_SERVER_TCP_PORT: 11101
      LOGSERVICE_SERVER_ADDRESS: perfectworld-logservice
      GACD_SERVER_ADDRESS: 0.0.0.0
      GACD_ANTICHEAT_SERVER_PORT: 29702
      GACD_CONTROL_SERVER_PORT: 29712
      TZ: Asia/Jakarta
    image: ossperfectworld/perfect-world-gacd:latest
    networks:
      - infrastructure
  perfectworld-gamed:
    container_name: perfectworld-gamed
    depends_on:
        - perfectworld-glinkd
    restart: always
    environment:
      GDELIVERYD_SERVER_ADDRESS: perfectworld-gdeliveryd
      GDELIVERYD_PROVIDER_SERVER_PORT: 29300
      GAMEDBD_SERVER_ADDRESS: perfectworld-gamedbd
      GAMEDBD_SERVER_PORT: 29400
      LOGSERVICE_SERVER_UDP_PORT: 11100
      LOGSERVICE_SERVER_TCP_PORT: 11101
      LOGSERVICE_SERVER_ADDRESS: perfectworld-logservice
      GFACTIOND_SERVER_ADDRESS: perfectworld-gfactiond
      GPROVIDER_SERVER_PORT: 29600
      GLINKD_SERVER_ADDRESS: perfectworld-glinkd
      GLINKD_DELIVERY_SERVER_1_PORT: 29301
      GLINKD_DELIVERY_SERVER_2_PORT: 29302
      GLINKD_DELIVERY_SERVER_3_PORT: 29303
      GLINKD_DELIVERY_SERVER_4_PORT: 29304
      GLINKD_DELIVERY_SERVER_5_PORT: 29305
      GLINKD_DELIVERY_SERVER_6_PORT: 29306
      GLINKD_DELIVERY_SERVER_7_PORT: 29307
      TZ: Asia/Jakarta
    image: ossperfectworld/perfect-world-gamed:latest
    networks:
      - infrastructure
  perfectworld-gamedbd:
    container_name: perfectworld-gamedbd
    depends_on:
        - perfectworld-authd
    expose:
      - "29400/tcp"
    restart: always
    volumes:
      - perfectworld-dbhomewdb-volume:/home/dbhomewdb
      - perfectworld-backupwdb-volume:/home/backupwdb
    environment:
      LOGSERVICE_SERVER_UDP_PORT: 11100
      LOGSERVICE_SERVER_TCP_PORT: 11101
      LOGSERVICE_SERVER_ADDRESS: perfectworld-logservice
      GAMEDBD_SERVER_ADDRESS: 0.0.0.0
      GAMEDBD_SERVER_PORT: 29400
      TZ: Asia/Jakarta
    image: ossperfectworld/perfect-world-gamedbd:latest
    networks:
      - infrastructure
  perfectworld-gdeliveryd:
    container_name: perfectworld-gdeliveryd
    depends_on:
        - perfectworld-gfactiond
    expose:
      - "29300/tcp"
      - "29100/tcp"
    restart: always
    environment:
      LOGSERVICE_SERVER_UDP_PORT: 11100
      LOGSERVICE_SERVER_TCP_PORT: 11101
      LOGSERVICE_SERVER_ADDRESS: perfectworld-logservice
      AUTHD_SERVER_ADDRESS: perfectworld-authd
      AUTHD_SERVER_PORT: 29200
      UNIQUENAMED_SERVER_ADDRESS: perfectworld-uniquenamed
      UNIQUENAMED_SERVER_PORT: 29401
      GAMEDBD_SERVER_ADDRESS: perfectworld-gamedbd
      GAMEDBD_SERVER_PORT: 29400
      GACD_SERVER_ADDRESS: perfectworld-gacd
      GACD_ANTICHEAT_SERVER_PORT: 29702
      GFACTIOND_SERVER_ADDRESS: perfectworld-gfactiond
      GFACTION_SERVER_PORT: 29500
      GDELIVERYD_SERVER_ADDRESS: 0.0.0.0
      GDELIVERYD_PROVIDER_SERVER_PORT: 29300
      GDELIVERYD_SERVER_PORT: 29100
      TZ: Asia/Jakarta
    image: ossperfectworld/perfect-world-gdeliveryd:latest
    networks:
      - infrastructure
  perfectworld-gfactiond:
    container_name: perfectworld-gfactiond
    depends_on:
        - perfectworld-gacd
    expose:
      - "29500/tcp"
      - "29600/tcp"
    restart: always
    environment:
      LOGSERVICE_SERVER_UDP_PORT: 11100
      LOGSERVICE_SERVER_TCP_PORT: 11101
      LOGSERVICE_SERVER_ADDRESS: perfectworld-logservice
      GFACTIOND_SERVER_ADDRESS: 0.0.0.0
      GFACTION_SERVER_PORT: 29500
      GPROVIDER_SERVER_PORT: 29600
      GAMEDBD_SERVER_ADDRESS: perfectworld-gamedbd
      GAMEDBD_SERVER_PORT: 29400
      UNIQUENAMED_SERVER_ADDRESS: perfectworld-uniquenamed
      UNIQUENAMED_SERVER_PORT: 29401
      TZ: Asia/Jakarta
    image: ossperfectworld/perfect-world-gfactiond:latest
    networks:
      - infrastructure
  perfectworld-glinkd:
    container_name: perfectworld-glinkd
    depends_on:
        - perfectworld-gdeliveryd
    ports:
    - "${PUBLIC_IP}:29000:29000"
    expose:
      - "29000/tcp"
      - "29001/tcp"
      - "29002/tcp"
      - "29003/tcp"
      - "29004/tcp"
      - "29005/tcp"
      - "29006/tcp"
      - "29301/tcp"
      - "29302/tcp"
      - "29303/tcp"
      - "29304/tcp"
      - "29305/tcp"
      - "29306/tcp"
      - "29307/tcp"
    restart: always
    environment:
      LOGSERVICE_SERVER_UDP_PORT: 11100
      LOGSERVICE_SERVER_TCP_PORT: 11101
      LOGSERVICE_SERVER_ADDRESS: perfectworld-logservice
      GFACTIOND_SERVER_ADDRESS: perfectworld-gfactiond
      GFACTION_SERVER_PORT: 29500
      GDELIVERYD_SERVER_ADDRESS: perfectworld-gdeliveryd
      GDELIVERYD_SERVER_PORT: 29100
      GLINKD_SERVER_ADDRESS: 0.0.0.0
      GLINKD_SERVER_1_PORT: 29000
      GLINKD_SERVER_2_PORT: 29001
      GLINKD_SERVER_3_PORT: 29002
      GLINKD_SERVER_4_PORT: 29003
      GLINKD_SERVER_5_PORT: 29004
      GLINKD_SERVER_6_PORT: 29005
      GLINKD_SERVER_7_PORT: 29006
      GLINKD_DELIVERY_SERVER_1_PORT: 29301
      GLINKD_DELIVERY_SERVER_2_PORT: 29302
      GLINKD_DELIVERY_SERVER_3_PORT: 29303
      GLINKD_DELIVERY_SERVER_4_PORT: 29304
      GLINKD_DELIVERY_SERVER_5_PORT: 29305
      GLINKD_DELIVERY_SERVER_6_PORT: 29306
      GLINKD_DELIVERY_SERVER_7_PORT: 29307
      TZ: Asia/Jakarta
    image: pw_glinkd:latest
    build:
      context: ./glinkd
      dockerfile: Dockerfile
    networks:
      - infrastructure
  perfectworld-logservice:
    container_name: perfectworld-logservice
    # depends_on:
    #     - perfectworld-db
    expose:
      - "11100/udp"
      - "11101/tcp"
    restart: always
    environment:
      LOGSERVICE_SERVER_UDP_PORT: 11100
      LOGSERVICE_SERVER_TCP_PORT: 11101
      LOGSERVICE_SERVER_ADDRESS: 0.0.0.0
      TZ: Asia/Jakarta
    image: ossperfectworld/perfect-world-logservice:latest
    networks:
      - infrastructure
  perfectworld-uniquenamed:
    container_name: perfectworld-uniquenamed
    depends_on:
        - perfectworld-logservice
    expose:
      - "29401/tcp"
    restart: always
    environment:
      LOGSERVICE_SERVER_UDP_PORT: 11100
      LOGSERVICE_SERVER_TCP_PORT: 11101
      LOGSERVICE_SERVER_ADDRESS: perfectworld-logservice
      UNIQUENAMED_SERVER_ADDRESS: 0.0.0.0
      UNIQUENAMED_SERVER_PORT: 29401
      TZ: Asia/Jakarta
    image: ossperfectworld/perfect-world-uniquenamed:latest
    networks:
      - infrastructure
  perfectworld-website-register:
    container_name: perfectworld-website-register
    ports:
    - "${PUBLIC_IP}:80:80"
    expose:
      - "80/tcp"
    environment:
      MYSQL_ADDRESS: ${DB_HOST}
      MYSQL_DB: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      USER_GOLD: ${USER_DEFAULT_GOLD}
      TZ: Asia/Jakarta
    image: pw_web_server:latest
    build: 
      context: ./web
      dockerfile: Dockerfile
    networks:
      - infrastructure

volumes:
  perfectworld-mysql-volume:
  perfectworld-dbhomewdb-volume:
  perfectworld-backupwdb-volume:
 
networks:
  infrastructure:
